services:
  initial_setup:
    image: busybox
    command: sh -c "mkdir -p /init/data/postgres /init/data/logs && chown -R 1000:1000 /init/data"
    volumes:
      - .:/init
    profiles:
      - initial_setup

#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file: .env
#    ports:
#      - "5000:8080"
#    volumes:
#      - ./data/logs:/app/logs
#    depends_on:
#      postgres_db:
#        condition: service_healthy
#      selenium:
#        condition: service_started

  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: '2g'
    ports:
      - "4444:4444"
      - "7900:7900"

  postgres_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
