services:

  init:
    image: busybox
    command: sh -c "mkdir -p /init/data/postgres /init/data/logs && chown -R 1000:1000 /init/data"
    volumes:
      - .:/init
    profiles:
      - setup
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "5000:80"
    volumes:
      - ./data/logs:/app/logs
    depends_on:
      db:
        condition: service_started
      selenium:
        condition: service_started

  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: '2g'
    ports:
      - "4444:4444"
      - "7900:7900"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/postgres
