// <auto-generated />
using System;
using JobScraper.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobScraper.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241202101853_ScrapingPolicy")]
    partial class ScrapingPolicy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobScraper.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("City");
                });

            modelBuilder.Entity("JobScraper.Domain.Entities.JobListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JobType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScrapedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WebsiteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("WebsiteId");

                    b.ToTable("JobListing");
                });

            modelBuilder.Entity("JobScraper.Domain.Entities.ScrapingError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ErrorType")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ScrapingError");
                });

            modelBuilder.Entity("JobScraper.Domain.Entities.ScrapingPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("CooldownPeriod")
                        .HasColumnType("interval");

                    b.Property<int>("RequestsPerMinute")
                        .HasColumnType("integer");

                    b.Property<bool>("ShouldRespectRobotsTxt")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ScrapingPolicies");
                });

            modelBuilder.Entity("JobScraper.Domain.Entities.Website", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastScraped")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ScrapingPolicyId")
                        .HasColumnType("integer");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ScrapingPolicyId");

                    b.ToTable("Websites");
                });

            modelBuilder.Entity("ScrapingErrorWebsite", b =>
                {
                    b.Property<int>("ScrapingErrorsId")
                        .HasColumnType("integer");

                    b.Property<int>("WebsitesId")
                        .HasColumnType("integer");

                    b.HasKey("ScrapingErrorsId", "WebsitesId");

                    b.HasIndex("WebsitesId");

                    b.ToTable("ScrapingErrorWebsite");
                });

            modelBuilder.Entity("JobScraper.Domain.Entities.JobListing", b =>
                {
                    b.HasOne("JobScraper.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobScraper.Domain.Entities.Website", "Website")
                        .WithMany("JobsListings")
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Website");
                });

            modelBuilder.Entity("JobScraper.Domain.Entities.Website", b =>
                {
                    b.HasOne("JobScraper.Domain.Entities.ScrapingPolicy", "ScrapingPolicy")
                        .WithMany("Websites")
                        .HasForeignKey("ScrapingPolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScrapingPolicy");
                });

            modelBuilder.Entity("ScrapingErrorWebsite", b =>
                {
                    b.HasOne("JobScraper.Domain.Entities.ScrapingError", null)
                        .WithMany()
                        .HasForeignKey("ScrapingErrorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobScraper.Domain.Entities.Website", null)
                        .WithMany()
                        .HasForeignKey("WebsitesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobScraper.Domain.Entities.ScrapingPolicy", b =>
                {
                    b.Navigation("Websites");
                });

            modelBuilder.Entity("JobScraper.Domain.Entities.Website", b =>
                {
                    b.Navigation("JobsListings");
                });
#pragma warning restore 612, 618
        }
    }
}
